### PR TITLE
Added fuzzy searching for build orders

### PR DESCRIPTION
**Pull request by Gvanderl**
I introduced the overlay to some friends who requested this feature. This allows the user to find a build order even if there are some typos in the search bar. It does add a dependency (thefuzz) but it's only a 56KB library along with python-Levenshtein (< 1 KB) for a significant speedup in search times.

### CODE REVIEW

**Comment by CraftySalamander** [comment]
Hey. Nice addition.
I did not yet test it, I would like first to finish with the integration of your previous contribution.
Unfortunately, I do not have time to look at this this week.

**Comment by CraftySalamander** [comment]
@Gvanderl 
Thank you for your nice contributions.
Everything is now included in the release 1.3.4 that I just published.

You will see that there are a few changes.
In particular, if you test the 'all in scouts', the tooltip now use images of the resources (sheep, boar, berry...).
For the fuzzy search, I added some additional options that you can read in the Readme.md.

**Comment by Gvanderl** [comment]
Just looked at the updates, it looks great! Thanks for incorporating all of those changes.

**Comment by CraftySalamander** [comment]
You are welcome.

**Pull request merged**
